# Generated by Django 6.0.1 on 2026-04-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_postbasemodel_created_at_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postbasemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media_files'),
        ),
    ]
