# Generated by Django 6.0.1 on 2026-08-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_postbasemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postbasemodel',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
