# Generated by Django 6.0.1 on 2026-08-30 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_postbasemodel_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postbasemodel',
            options={'permissions': [('can_approve_post', 'Can approve post base model')]},
        ),
    ]
